'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, Beef, CalendarDays, Check, ChevronLeft, ChevronRight, Dumbbell, Flame, Footprints, Moon, Plus, Scale, Trophy, X } from 'lucide-react';

type SetRow={id:number;weight:string;reps:string;done:boolean}; type Exercise={id:number;name:string;muscle:string;sets:SetRow[]}; type Day={date:string;workoutDone:boolean;foodDone:boolean;steps:number;mood:number;busy:boolean;weight?:string;exercises:Exercise[];food:string};
const today=new Date(), iso=(d:Date)=>d.toISOString().slice(0,10), months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'], week=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const blank=(date:string):Day=>({date,workoutDone:false,foodDone:false,steps:0,mood:3,busy:false,exercises:[],food:''});
const muscles:[string,number,string][]=[['Грудь',76,'gold-3'],['Спина',69,'gold-2'],['Ноги',54,'silver-3'],['Плечи',42,'silver-2'],['Руки',35,'silver-1'],['Кор',18,'bronze-2']];
function Rank({rank}:{rank:string}){const [tier,level]=rank.split('-');return <span className={`rank ${tier}`}><Trophy size={15}/><b>{level}</b></span>}
function monthDays(date:Date){const start=new Date(date.getFullYear(),date.getMonth(),1),arr:(Date|null)[]=new Array((start.getDay()+6)%7).fill(null),last=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();for(let n=1;n<=last;n++)arr.push(new Date(date.getFullYear(),date.getMonth(),n));while(arr.length%7)arr.push(null);return arr}

export default function Home(){
 const [selected,setSelected]=useState(iso(today)),[cursor,setCursor]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[log,setLog]=useState(false),[foodModal,setFoodModal]=useState(false),[weightModal,setWeightModal]=useState(false),[stepsModal,setStepsModal]=useState(false),[settings,setSettings]=useState(false),[newEx,setNewEx]=useState(''),[newMuscle,setNewMuscle]=useState('Спина'),[foodDraft,setFoodDraft]=useState(''),[weightDraft,setWeightDraft]=useState(''),[stepsDraft,setStepsDraft]=useState(''),[nameDraft,setNameDraft]=useState(''),[profile,setProfile]=useState<string|undefined>(undefined),[view,setView]=useState('today');
 const [days,setDays]=useState<Record<string,Day>>({});
 const active=days[selected]??blank(selected), dates=useMemo(()=>monthDays(cursor),[cursor]), streak=useMemo(()=>{let c=0,d=new Date(today);while(days[iso(d)]?.workoutDone||days[iso(d)]?.foodDone){c++;d.setDate(d.getDate()-1)}return Math.max(1,c)},[days]), recordStreak=useMemo(()=>{let best=0,count=0,previous='';for(const key of Object.keys(days).filter(k=>days[k].workoutDone||days[k].foodDone).sort()){const prior=new Date(key);prior.setDate(prior.getDate()-1);count=iso(prior)===previous?count+1:1;previous=key;best=Math.max(best,count)}return Math.max(streak,best)},[days,streak]), weigh=(d:Date)=>(d.getDate()+streak)%7===0,deload=Math.max(1,28-recordStreak%28);
 useEffect(()=>{fetch('/api/days').then(r=>r.ok?r.json():null).then(data=>{if(data?.days?.length)setDays(prev=>({...prev,...Object.fromEntries(data.days.map((d:Day)=>[d.date,d]))}))}).catch(()=>undefined);fetch('/api/profile').then(r=>r.ok?r.json():null).then(data=>setProfile(data?.profile?.name??null)).catch(()=>setProfile(null))},[]);
 const patch=(v:Partial<Day>)=>setDays(x=>{const next={...(x[selected]??blank(selected)),...v};void fetch('/api/days',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)}).catch(()=>undefined);return {...x,[selected]:next}});
 const setRow=(e:number,s:number,k:keyof SetRow,v:string|boolean)=>patch({exercises:active.exercises.map(x=>x.id!==e?x:{...x,sets:x.sets.map(q=>q.id!==s?q:{...q,[k]:v})})});
 const addSet=(e:number)=>patch({exercises:active.exercises.map(x=>x.id!==e?x:{...x,sets:[...x.sets,{id:Date.now(),weight:'',reps:'',done:false}]})});
 const addExercise=()=>{if(!newEx.trim())return;patch({exercises:[...active.exercises,{id:Date.now(),name:newEx.trim(),muscle:newMuscle,sets:[{id:Date.now()+1,weight:'',reps:'',done:false}]}]});setNewEx('')};
 const jump=(target:string,nextView:string)=>{setView(nextView);document.getElementById(target)?.scrollIntoView({behavior:'smooth',block:'start'})};
 if(profile===null)return <main className="welcome"><section><span className="brand-mark"><Flame size={24}/></span><p className="eyebrow">ПЕРВЫЙ ВХОД</p><h1>Создай свой трекер</h1><p>Данные сохраняются только в твоём профиле. Как к тебе обращаться?</p><input value={nameDraft} onChange={e=>setNameDraft(e.target.value)} placeholder="Имя" autoFocus/><button className="primary-btn" onClick={()=>fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:nameDraft})}).then(r=>r.ok&&setProfile(nameDraft.trim()))}>Продолжить</button></section></main>;
 return <main className="app-shell"><aside className="side-nav"><div className="brand"><span className="brand-mark"><Flame size={20}/></span><span>FORGE</span></div><nav><button className={view==='today'?'nav-active':''} onClick={()=>{setView('today');window.scrollTo({top:0,behavior:'smooth'})}}><Activity size={18}/>Сегодня</button><button className={view==='calendar'?'nav-active':''} onClick={()=>jump('calendar','calendar')}><CalendarDays size={18}/>Календарь</button><button className={view==='progress'?'nav-active':''} onClick={()=>jump('plan','progress')}><Dumbbell size={18}/>Прогресс</button><button className={view==='muscles'?'nav-active':''} onClick={()=>jump('muscles','muscles')}><Beef size={18}/>Мышцы</button></nav><div className="side-bottom"><span className="tiny-label">ТЕКУЩАЯ СЕРИЯ</span><div className="side-streak"><Flame size={20}/><b>{streak}</b> дней</div><button className="account-button" onClick={()=>setSettings(true)}>{profile||'Профиль'} · настройки</button></div></aside>
 <section className="content"><header className="topline"><div><p className="eyebrow">{selected}</p><h1>Твой день, {profile||'спортсмен'}</h1></div><button className="profile" onClick={()=>setSettings(true)}>{(profile||'Л')[0]} <span>⌄</span></button></header><div className="hero-grid"><section className="streak-card"><div className="flame-orb"><Flame size={41} fill="currentColor"/></div><div><p className="eyebrow light">СЕРИЯ В РАБОТЕ</p><div className="streak-number">{streak}<span>дней подряд</span></div><p className="muted-on-dark">Любая запись за день поддерживает серию.</p></div><div className="streak-track"><span style={{width:`${Math.min(100,streak/14*100)}%`}}/></div><small>До следующего этапа: {Math.max(0,14-streak)} дней</small></section></div>
 <section className="quick-grid"><button className="quick-card workout" onClick={()=>setLog(true)}><span className="quick-icon"><Dumbbell size={20}/></span><span><b>{active.workoutDone?'Тренировка готова':'Записать тренировку'}</b><small>{active.exercises.length?`${active.exercises.length} упражнения`:'Подходы, повторы, вес'}</small></span><Plus size={18}/></button><button className="quick-card food" onClick={()=>{setFoodDraft(active.food);setFoodModal(true)}}><span className="quick-icon"><Beef size={20}/></span><span><b>{active.foodDone?'Питание отмечено':'Что ты ел?'}</b><small>{active.foodDone?'День сохранён':'Короткая запись без подсчётов'}</small></span><Plus size={18}/></button><button className="quick-card steps" onClick={()=>{setStepsDraft(String(active.steps||''));setStepsModal(true)}}><span className="quick-icon"><Footprints size={20}/></span><span><b>{active.steps.toLocaleString('ru-RU')} шагов</b><small>Ввести точное количество</small></span><Plus size={18}/></button></section>
 <section id="calendar" className="section-head"><div><p className="eyebrow">НЕДЕЛЯ В ОДНОМ ВЗГЛЯДЕ</p><h2>Ритм и план</h2></div><button className="ghost-btn" onClick={()=>setCursor(new Date(today.getFullYear(),today.getMonth(),1))}>Сегодня</button></section><section className="calendar-card"><div className="calendar-top"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft size={18}/></button><b>{months[cursor.getMonth()]} {cursor.getFullYear()}</b><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight size={18}/></button></div><div className="calendar">{week.map(x=><span className="week-name" key={x}>{x}</span>)}{dates.map((d,i)=>{if(!d)return <span key={i}/>;const k=iso(d),r=days[k];return <button key={k} onClick={()=>setSelected(k)} className={`day ${k===selected?'selected':''} ${r?.busy?'busy':''} ${weigh(d)?'weigh':''}`}><span>{d.getDate()}</span>{r?.workoutDone&&<i className="dot train"/>}{r?.foodDone&&<i className="dot meal"/>}{r?.busy&&<i className="busy-mark">●</i>}</button>})}</div><div className="calendar-legend"><span><i className="dot train"/> тренировка</span><span><i className="dot meal"/> питание</span><span><i className="yellow-dot"/> взвешивание</span><span><i className="busy-dot"/> занят</span></div></section>
 <section className="bottom-grid"><section id="muscles" className="muscle-card"><div className="section-head compact"><div><p className="eyebrow">БАЛАНС НАГРУЗКИ</p><h2>Мышечный радар</h2></div><span className="status-chip">за 14 дней</span></div><p className="hint">Чем ниже шкала, тем ниже ранг. Начни со слабого звена.</p><div className="muscle-list">{muscles.map(([n,v,r])=><div className="muscle-row" key={n}><span>{n}</span><div className="meter"><i style={{width:`${v}%`}}/></div><Rank rank={r}/></div>)}</div></section><section id="plan" className="plan-card"><p className="eyebrow">НЕ ПЕРЕГОРИ</p><h2>Дни восстановления</h2><div className="deload-ring"><b>{deload}</b><span>дней</span></div><p>Личный рекорд: {recordStreak} дн. Через {deload} дн. запланируй разгрузочную неделю: оставить технику, снизить рабочий объём примерно на треть.</p><button className="outline-btn" onClick={()=>patch({busy:!active.busy})}>{active.busy?<><Check size={16}/> День занят</>:<><CalendarDays size={16}/> Отметить занятость</>}</button></section></section></section>
 <aside className="right-rail"><section className="rail-card"><div className="rail-title"><span><Scale size={18}/> Контроль веса</span><button onClick={()=>setWeightModal(true)}>+</button></div><div className="weight-value">{active.weight||'—'} <small>кг</small></div><p>Следующее взвешивание подсвечено жёлтым в календаре. Ориентир — раз в 7 дней.</p></section><section className="rail-card feelings"><div className="rail-title"><span><Moon size={18}/> Самочувствие</span></div><p>Как ты сегодня?</p><div className="moods">{['😵','😕','😐','🙂','⚡'].map((m,i)=><button key={m} className={active.mood===i+1?'mood-active':''} onClick={()=>patch({mood:i+1})}>{m}</button>)}</div><textarea placeholder="Короткая заметка для себя"/></section><section className="rail-card focus"><p className="eyebrow">МИКРО-ЦЕЛЬ</p><h3>8 000 шагов</h3><div className="goal-line"><i style={{width:`${Math.min(100,active.steps/8000*100)}%`}}/></div><p>{Math.max(0,8000-active.steps).toLocaleString('ru-RU')} осталось до цели</p></section></aside>
 {log&&<div className="modal-backdrop"><section className="modal workout-modal"><button className="close" onClick={()=>setLog(false)}><X/></button><p className="eyebrow">ДНЕВНИК ТРЕНИРОВКИ</p><h2>Что сделал сегодня?</h2><p className="modal-sub">Впиши вес и повторы в каждом подходе. Галочка означает, что подход закончен.</p><div className="exercise-list">{active.exercises.map(ex=><div className="exercise-box" key={ex.id}><div className="exercise-title"><div><b>{ex.name}</b><span>{ex.muscle}</span></div><button onClick={()=>patch({exercises:active.exercises.filter(x=>x.id!==ex.id)})}><X size={16}/></button></div><div className="set-head"><span>СЕТ</span><span>ВЕС, КГ</span><span>ПОВТОРЫ</span><span>ГОТОВО</span></div>{ex.sets.map((s,i)=><div className="set-row" key={s.id}><span>{i+1}</span><input value={s.weight} onChange={e=>setRow(ex.id,s.id,'weight',e.target.value)} inputMode="decimal" placeholder="0"/><input value={s.reps} onChange={e=>setRow(ex.id,s.id,'reps',e.target.value)} inputMode="numeric" placeholder="0"/><button className={`done-set ${s.done?'checked':''}`} onClick={()=>setRow(ex.id,s.id,'done',!s.done)}>{s.done&&<Check size={15}/>}</button></div>)}<button className="add-set" onClick={()=>addSet(ex.id)}><Plus size={15}/> Добавить подход</button></div>)}</div><div className="add-exercise"><input value={newEx} onChange={e=>setNewEx(e.target.value)} placeholder="Название упражнения"/><select value={newMuscle} onChange={e=>setNewMuscle(e.target.value)}>{['Грудь','Спина','Ноги','Плечи','Руки','Кор'].map(x=><option key={x}>{x}</option>)}</select><button onClick={addExercise}><Plus size={16}/> Упражнение</button></div><button className="primary-btn" onClick={()=>{patch({workoutDone:true});setLog(false)}}><Check size={18}/> Завершить тренировку</button></section></div>}
 {foodModal&&<div className="modal-backdrop"><section className="modal small-modal"><button className="close" onClick={()=>setFoodModal(false)}><X/></button><p className="eyebrow">ПИТАНИЕ</p><h2>Что было сегодня?</h2><p className="modal-sub">Без сложного подсчёта: короткая запись поможет замечать привычки.</p><textarea value={foodDraft} onChange={e=>setFoodDraft(e.target.value)} placeholder="Например: овсянка, паста с курицей, яблоко..."/><button className="primary-btn" onClick={()=>{patch({food:foodDraft,foodDone:true});setFoodModal(false)}}><Check size={18}/> Сохранить питание</button></section></div>}
 {weightModal&&<div className="modal-backdrop"><section className="modal small-modal"><button className="close" onClick={()=>setWeightModal(false)}><X/></button><p className="eyebrow">КОНТРОЛЬ ВЕСА</p><h2>Утренний вес</h2><p className="modal-sub">Взвешивайся утром, после туалета, до еды. Смотри на динамику, а не на один день.</p><div className="weight-input"><input value={weightDraft} onChange={e=>setWeightDraft(e.target.value)} placeholder="73.0" inputMode="decimal"/><span>кг</span></div><button className="primary-btn" onClick={()=>{patch({weight:weightDraft});setWeightModal(false)}}><Check size={18}/> Сохранить вес</button></section></div>}
 {stepsModal&&<div className="modal-backdrop"><section className="modal small-modal"><button className="close" onClick={()=>setStepsModal(false)}><X/></button><p className="eyebrow">ШАГИ</p><h2>Точное число шагов</h2><p className="modal-sub">Введи любое значение, не только кратное тысяче.</p><div className="weight-input"><input value={stepsDraft} onChange={e=>setStepsDraft(e.target.value.replace(/[^0-9]/g,''))} placeholder="8420" inputMode="numeric"/><span>шагов</span></div><button className="primary-btn" onClick={()=>{patch({steps:Number(stepsDraft)||0});setStepsModal(false)}}><Check size={18}/> Сохранить шаги</button></section></div>}
 {settings&&<div className="modal-backdrop"><section className="modal small-modal"><button className="close" onClick={()=>setSettings(false)}><X/></button><p className="eyebrow">ПРОФИЛЬ</p><h2>{profile}</h2><p className="modal-sub">Твои данные привязаны к личному аккаунту и не смешиваются с другими пользователями.</p><button className="danger-btn" onClick={()=>{if(window.confirm('Удалить все записи этого профиля и начать с нуля?'))fetch('/api/days/reset',{method:'POST'}).then(r=>r.ok&&setDays({}));setSettings(false)}}>Начать заново</button></section></div>}</main>
}
