import { env } from 'cloudflare:workers';

const encoder = new TextEncoder();
const db = () => { if (!env.DB) throw new Error('D1 binding is unavailable'); return env.DB; };
const hex = (bytes: Uint8Array) => [...bytes].map(x => x.toString(16).padStart(2, '0')).join('');
const random = (size = 24) => { const bytes = new Uint8Array(size); crypto.getRandomValues(bytes); return hex(bytes); };
async function passwordHash(password: string, salt: string) { const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: encoder.encode(salt), iterations: 100000, hash: 'SHA-256' }, key, 256); return hex(new Uint8Array(bits)); }
export async function register(name: string, email: string, password: string) { const cleanName = name.trim().slice(0, 40), cleanEmail = email.trim().toLowerCase(); if (!cleanName || !/^\S+@\S+\.\S+$/.test(cleanEmail) || password.length < 8) throw new Error('Укажи имя, корректный email и пароль от 8 символов'); const salt = random(16), hash = await passwordHash(password, salt), userId = crypto.randomUUID(); try { await db().prepare('INSERT INTO accounts (user_id, display_name, email, password_hash, password_salt, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(userId, cleanName, cleanEmail, hash, salt, new Date().toISOString()).run(); return { userId, name: cleanName }; } catch { throw new Error('Этот email уже зарегистрирован'); } }
export async function login(email: string, password: string) { const account = await db().prepare('SELECT user_id, display_name, password_hash, password_salt FROM accounts WHERE email = ?').bind(email.trim().toLowerCase()).first<{user_id:string;display_name:string;password_hash:string;password_salt:string}>(); if (!account || await passwordHash(password, account.password_salt) !== account.password_hash) throw new Error('Неверный email или пароль'); return { userId: account.user_id, name: account.display_name }; }
export async function createSession(userId: string) { const token = random(32), expires = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(); await db().prepare('INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)').bind(token, userId, expires).run(); return token; }
export async function getUser(request: Request) { const token = request.headers.get('Cookie')?.match(/(?:^|; )forge_session=([^;]+)/)?.[1]; if (!token) return null; const user = await db().prepare('SELECT a.user_id, a.display_name FROM sessions s JOIN accounts a ON a.user_id = s.user_id WHERE s.token = ? AND s.expires_at > ?').bind(token, new Date().toISOString()).first<{user_id:string;display_name:string}>(); return user ? { id:user.user_id, name:user.display_name } : null; }
export const sessionCookie = (token: string) => `forge_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`;
export async function logout(request: Request) { const token = request.headers.get('Cookie')?.match(/(?:^|; )forge_session=([^;]+)/)?.[1]; if (token) await db().prepare('DELETE FROM sessions WHERE token = ?').bind(token).run(); }
